version: '3.9'

services:
  sponect-frontend:
    build: ./frontend
    container_name: sponect-frontend
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env
    depends_on:
      - sponect-backend
    networks:
      - app-network

  sponect-backend:
    build: ./backend
    container_name: sponect-backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    environment:
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      DB_PORT: 3306
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8
    container_name: db
    restart: always
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3307:3306"
    volumes:
      - sql-data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:

volumes:
  sql-data:
